name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to upload assets to releases
      attestations: write # to upload assets attestation for build provenance
      id-token: write # grant additional permission to attestation action to mint the OIDC token permission

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: |
        go get ./...
        go build -buildmode=c-shared -o fsguard.so -v ./...

    - name: Upload Release Asset
      if: github.repository == 'Vanilla-OS/vib-fsguard'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          fsguard.so
    
    - name: Attest Generated Files
      if: github.repository == 'Vanilla-OS/vib-fsguard'
      id: attest
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'fsguard.so'
